### ISSUE TITLE
Go migrations are broken

### ISSUE THREAD

**Issue by ralfthewise** [steinbacher/goose#7]
The template for go migrations names the functions `Up_...`, but the migration runner title cases the function names in the generated files which end up being `UP_...`

https://github.com/steinbacher/goose/blob/master/lib/goose/templates/migration.go.tmpl#L8

https://github.com/steinbacher/goose/blob/master/lib/goose/migration_go.go#L65

**Comment by zabawaba99** [comment]
Thanks for pointing that out. Will address it shortly.

**Comment by zabawaba99** [comment]
@ralfthewise I made a fix in #8 and added some tests around go migrations which weren't there. Let me know if you have any other issues.

**Comment by ralfthewise** [comment]
Awesome, thanks @zabawaba99 , will test on monday!
